name       : wofi
version    : "1.3"
release    : 1
source     :
    - https://hg.sr.ht/~scoopta/wofi/archive/v1.3.tar.gz : 7644e4e995bc027b7f3f411ceda82b3e2a72a4a424f6193663c27bbf00f23067
homepage   : https://hg.sr.ht/~scoopta/wofi
license    : GPL-3.0
component  : desktop
summary    : Wofi is a launcher/menu program for wlroots based wayland compositors such as sway.
description: |
    Wofi is a launcher/menu program for wlroots based wayland compositors such as sway.
builddeps  :
  - wayland-devel
  - libgtk-3-devel
  - pkg-config
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
