name       : pamixer
version    : "1.6"
release    : 1
source     :
    - https://github.com/cdemoulins/pamixer/archive/refs/tags/1.6.tar.gz : 8b7199e495dc19b190f8f02ace8782f533266a4bd7c7d3cf6f4cf09b2de13e71
homepage   : https://github.com/cdemoulins/pamixer
license    : GPL-3.0-or-later
component  : desktop
summary    : Pulseaudio command line mixer
description: |
  Pulseaudio command line mixer
builddeps  :
  - pkgconfig(cxxopts)
  - pkgconfig(libpulse)
  - cmake
  - meson
  - ninja
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
