name       : hyprland
version    : 0.34.0
release    : 1
source     :
    - https://github.com/hyprwm/Hyprland/releases/download/v0.34.0/source-v0.34.0.tar.gz : 234500dc726ec6cd190d95d45cf6d04766064172e75c1351ee7c49ec3405497e
homepage   : https://github.com/hyprwm/Hyprland
license    : BSD
component  : desktop
summary    : A highly customizable dynamic tiling Wayland compositor.
description: |
  A highly customizable dynamic tiling Wayland compositor.
builddeps  :
  - pkgconfig(cairo)
  - pkgconfig(egl)
  - pkgconfig(gbm)
  - pkgconfig(gl)
  - pkgconfig(glesv2)
  - pkgconfig(libdrm)
  - pkgconfig(libinput)
  - pkgconfig(libseat)
  - pkgconfig(libudev)
  - pkgconfig(pango)
  - pkgconfig(pangocairo)
  - pkgconfig(pixman-1)
  - pkgconfig(vulkan)
  - pkgconfig(wayland-client)
  - pkgconfig(wayland-protocols)
  - pkgconfig(wayland-scanner)
  - pkgconfig(wayland-server)
  - pkgconfig(xcb)
  - pkgconfig(xcb-icccm)
  - pkgconfig(xcb-renderutil)
  - pkgconfig(xkbcommon)
  - pkgconfig(xwayland)
  - glibc-devel
  - jq
  - tomlplusplus-devel
  - wlroots-devel
setup      : |
  %meson_configure
build      : |
  %ninja_build
install    : |
  %ninja_install
